name: Simple CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install flake8

    - name: Lint Code
      run: |
        flake8 .

    - name: Build
      run: |
        echo "Build stage (e.g., compiling or packaging)"
        mkdir -p dist && echo "Build complete" > dist/output.txt

    - name: Deploy (Optional)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Simulating deployment..."
